version: '3'
services:

    mongodb:
        image: mongo:4.2.3
        ports:
            - "27017:27017"
        container_name: euapi_mongodb
        restart: unless-stopped
        command: mongod --auth
        environment:
            MONGO_INITDB_ROOT_USERNAME: mongoroot
            MONGO_INITDB_ROOT_PASSWORD: mongorootpassword
            MONGODB_DATA_DIR: /data/db
            MONDODB_LOG_DIR: /dev/null
            MONGODB_PROPDB: rentalproperties
            MONGODB_USERNAME: mongoflask
            MONGODB_PASSWORD: mongoflaskpassword
        volumes:
            - ./mongo/persistent:/data/db
            - ./mongo/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
        networks:
            - backend

networks:
    backend:
        driver: bridge

volumes:
    mongodbdata:
        driver: local